[workspace]
members = [
  "risc0/core",
  "risc0/zkp",
  "risc0/zkp/rust",
  "risc0/zkvm",
  "risc0/zkvm/circuit",
  "risc0/zkvm/circuit/make-circuit",
  "risc0/zkvm/platform",
  "risc0/zkvm/prove/make-id",
  "risc0/zkvm/r0vm",
  "risc0/zkvm/sdk/rust",
  "risc0/zkvm/sdk/rust/build",
  "risc0/zkvm/sdk/rust/circuit",
  "risc0/zkvm/sdk/rust/guestio",
  "risc0/zkvm/sdk/rust/guestio_derive",
]

exclude = [
  "risc0/zkvm/sdk/rust/cargo-risc0",
  "risc0/zkvm/sdk/rust/methods",
]

[profile.release]
lto = true

[profile.bootstrap]
inherits = "release"

[profile.dev.package.risc0-zkvm-circuit]
debug = false

[workspace.metadata.workspaces]
allow_branch = "main"
