[package]
name = "guestio_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "guestio_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[dev-dependencies]
guestio = { path = "../guestio" }
