[package]
name = "risc0-zkvm"
version = "0.10.0"
edition = "2021"
description = "RISC Zero zero-knowledge VM"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
bytemuck = "1.9"
risc0-zkp = { version = "0.10", path = "../../../zkp/rust", default-features = false }
risc0-zkvm-platform = { version = "0.10", path = "platform" }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
criterion = "0.3"
tempfile = "3.3"

# TODO(nils): Change these arch checks to vendor checks when we have a
# real target triple.
#
# Host dependencies
[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
anyhow = "1.0"
ctor = "0.1"
cxx = "1.0"
log = "0.4"
rand = "0.8"
risc0-zkvm-circuit = { version = "0.10.0", path = "circuit", optional = true }
risc0-zkvm-sys = { version = "0.10", path = "../.." }
sha2 = "0.10"
xmas-elf = "0.8"

[target.'cfg(not(target_arch = "riscv32"))'.dev-dependencies]
env_logger = "0.9"
risc0-zkvm-methods = { path = "methods" }

[features]
circuit = ["dep:risc0-zkvm-circuit"]
default = ["host", "prove", "std", "verify"]
doc = ["std"]
host = []
prove = ["circuit", "risc0-zkp/prove"]
std = ["risc0-zkp/std", "serde/std"]
verify = ["circuit", "risc0-zkp/verify"]
# Run rust-based prover instead of FFI-based prover.
pure-prove = ["prove", "std"]

[[bench]]
name = "guest_run"
harness = false

[[bench]]
name = "verify"
harness = false
